import org.jetbrains.intellij.platform.gradle.tasks.GenerateLexerTask
import org.jetbrains.intellij.platform.gradle.tasks.GenerateParserTask
import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.24"
    id("org.jetbrains.intellij.platform") version "2.16.0"
    id("org.jetbrains.intellij.platform.grammarkit") version "2.16.0"
}

group = "org.timbran.mica"
version = "0.1.2"

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        create("IC", "2024.1.4")
        testFramework(TestFrameworkType.Platform)
    }
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("junit:junit:4.13.2")
}

sourceSets {
    main {
        java.srcDirs("src/main/java", "src/main/gen", "src/main/kotlin")
    }
}

// Disable purgeOldFiles because both generation tasks share "src/main/gen" as their targetRootOutputDir.
// Enabling it would cause one task's execution to delete the outputs generated by the other task.
val generateParser = tasks.named<GenerateParserTask>("generateParser") {
    sourceFile.set(file("src/main/kotlin/org/timbran/mica/jetbrains/MicaParser.bnf"))
    targetRootOutputDir.set(file("src/main/gen"))
    purgeOldFiles.set(false)
}

val generateLexer = tasks.named<GenerateLexerTask>("generateLexer") {
    dependsOn(generateParser)
    sourceFile.set(file("src/main/kotlin/org/timbran/mica/jetbrains/MicaLexer.flex"))
    targetRootOutputDir.set(file("src/main/gen"))
    purgeOldFiles.set(false)
}

tasks.compileKotlin {
    dependsOn(generateLexer, generateParser)
}
tasks.compileJava {
    dependsOn(generateLexer, generateParser)
}

intellijPlatform {
    pluginConfiguration {
        id.set("org.timbran.mica.jetbrains")
        name.set("Mica Language Support")
        version.set(project.version.toString())
        description.set("Native language support for Mica, a live, relation-first programmable system.")
        
        vendor {
            name.set("Timbran")
        }
    }
}
